
# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: false
highlighter: rouge
lsi: false
future: true

# permalink: pretty
# /blog/:year/:month/:day/:title/

# Where things are
source:      .
destination: ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir: 		./_data
collections: null

# Handling Reading
include:      [".htaccess"]
exclude:      [vendor]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:     kramdown #redcarpet

# Site settings
title: "blog.eeearl.com"
email: ul7290@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
page.comments: True
twitter_username: earlpod
github_username:  ul7290

permalink: /:year-:month-:day-:title/